# [settings]

[build]
  base = "site"
  publish = "dist"
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build-preview"

[[redirects]]
  from = "https://ay-portfolio.netlify.com"
  to = "https://ayahya.me/:splat"
  status = 301
  force = true
   
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    